// apps/movie-quotes-frontend-vue/src/pages/add.vue
<script lang="ts">
import QuoteForm from '../components/QuoteForm.vue';
import type { QuoteFormData } from '../components/QuoteForm.vue';

import { getMovieId } from '../lib/quotes-api';
import { isPostRequest } from '../lib/request-utils';

export async function getData ({ req, reply }) {
  let formData: QuoteFormData = {}
  let saveError = false

  if (isPostRequest(req)) {
    formData = req.body
    const movieId = await getMovieId(req, formData.movie)

    if (!movieId) {
      saveError = true
    }
    const quote = {
      quote: formData.quote,
      saidBy: formData.saidBy,
      movieId,
    }

    try {
      await req.quotes.graphql({
        query: `
          mutation($quote: QuoteInput!) {
            saveQuote(input: $quote) {
              id
            }
          }
        `,
        variables: { quote },
      })
    } catch (error) {
      console.error(error)
      saveError = true
    }
    if (!saveError) {
      return reply.redirect('/')
    }
  }
  return {
    saveError,
    formData,
    page: 'add',
  }
}
</script>

<script lang="ts" setup>
import { useRouteContext } from '/:core.js'

const { saveError, formData } = useRouteContext().data
</script>

<template>
  <main>
    <h2>Add a quote</h2>
    <QuoteForm 
      action="/add" 
      :values="formData"
      :saveError="saveError"
      submitLabel="Add quote" />
  </main>
</template>

// apps/movie-quotes-frontend-htmx/src/pages/add.tsx
import QuoteForm from '/components/QuoteForm.tsx'
import type { QuoteFormData } from '/components/QuoteForm.tsx'

import { gql, quotesApi } from '/lib/quotes-api'
import { getFormData, isPostRequest } from '/lib/request-utils'

export const path = '/add'

export const head = (
  <>
    <title>Add a movie quote</title>
  </>
)

export default async ({ req, reply }) => {
  let formData: QuoteFormData = {}
  let saveError = false

  if (isPostRequest(req)) {
    formData = await getFormData(req)

    const movieId = await quotesApi.getMovieId(formData.movie)

    if (movieId) {
      const quote = {
        quote: formData.quote,
        saidBy: formData.saidBy,
        movieId,
      }

      const { error } = await quotesApi.mutation(
        gql`
        mutation($quote: QuoteInput!) {
          saveQuote(input: $quote) {
            id
          }
        }
      `,
        { quote },
      )

      if (!error) {
        return reply.redirect('/')
      }
      saveError = true
    } else {
      saveError = true
    }
  }
  req.page = 'Add'
  return (
    <main>
      <h2>Add a quote</h2>
      <QuoteForm
        action="/add"
        values={formData}
        saveError={saveError}
        submitLabel="Add quote"
      />
    </main>
  )
}
