// apps/movie-quotes-frontend-react/src/layouts/default.tsx
import { Link } from 'react-router-dom'
import { useRouteContext } from '/:core.jsx'

export default ({ children }) => {
  const navActiveClasses = 'font-bold bg-yellow-400 no-underline'
  const { page } = useRouteContext().data

  return (
    <>
      <header className="prose mx-auto mb-6">
        <h1>🎬 Movie Quotes</h1>
      </header>
      <nav className="prose mx-auto mb-6 border-y border-gray-200 flex">
        <Link
          to="/?sort=createdAt"
          className={`p-3 ${page === 'listing-createdAt' && navActiveClasses}`}
        >
          Latest quotes
        </Link>
        <Link
          to="/?sort=likes"
          className={`p-3 ${page === 'listing-likes' && navActiveClasses}`}
        >
          Top quotes
        </Link>
        <Link to="/add" className={`p-3 ${page === 'add' && navActiveClasses}`}>
          Add a quote
        </Link>
      </nav>
      <section className="prose mx-auto">{children}</section>
    </>
  )
}

// apps/movie-quotes-frontend-vue/src/layouts/default.vue
<script setup>
import { useRouteContext } from '/:core.js'
const { page } = useRouteContext().data
const navActiveClasses = 'font-bold bg-yellow-400 no-underline'
</script>

<template>
  <header class="prose mx-auto mb-6">
    <h1>🎬 Movie Quotes</h1>
  </header>
  <nav class="prose mx-auto mb-6 border-y border-gray-200 flex">
    <router-link to="/?sort=createdAt" :class="['p-3', page === 'listing-createdAt' ? navActiveClasses : '']">Latest quotes</router-link>
    <router-link to="/?sort=likes" :class="['p-3', page === 'listing-likes' ? navActiveClasses : '']">Top quotes</router-link>
    <router-link to="/add" :class="['p-3', page === 'add' ? navActiveClasses : '']">Add a quote</router-link>
  </nav>
  <section class="prose mx-auto">
    <slot />
  </section>
</template>
